Repository ProfCyberNaught/cybersecurity-blog-posts, pull requests merged in 2023-02, with the labels that each got.

#5 Add new article and update readme file
  README.md
  cybersecurity-what-is-malware.md
Labels: cybersecurity

#4 upload new article on cybersecurity and update readme
  README.md
  cybersecurity-which-operating-system-for-security-and-privacy.md
Labels: cybersecurity

#6 Created New Article
  README.md
  cybersecurity-what-colour-hacker-would-you-be.md
Labels: documentation, cybersecurity

#22 Update README.md
  README.md
Labels: documentation

#24 Update why-become-a-cybersecurity-engineer.md
  pcn_cybersecurity_articles/why-become-a-cybersecurity-engineer.md
Labels: documentation

#25 Update cybersecurity-navigating-the-digital-landscape.md
  pcn_cybersecurity_articles/cybersecurity-navigating-the-digital-landscape.md
Labels: documentation

#26 Update programming-or-scripting-languages-what-is-the-difference.md
  pcn_cybersecurity_articles/programming-or-scripting-languages-what-is-the-difference.md
Labels: documentation

#27 18 article update required
  pcn_cybersecurity_articles/cybersecurity-what-is-malware.md
Labels: documentation

#29 Update cybersecurity-what-colour-hacker-would-you-be.md
  pcn_cybersecurity_articles/cybersecurity-what-colour-hacker-would-you-be.md
Labels: documentation
